name: startup_script

on:
 workflow_dispatch:

jobs:
  script:
    runs-on : ubuntu-latest

    steps:
      - name: block style
        run: |
          sudo apt-get update 
          git -v

      - name: fold style
        run: >
         sudo apt-get update 
          git -v  




   
